# Generated by Django 4.2.4 on 2023-09-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_favorite_options_alter_shoppingcart_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-id'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=3, upload_to='recipes/images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
