# Generated by Django 4.2.4 on 2023-09-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=2, upload_to='recipes/images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
