# Generated by Django 4.2.4 on 2023-08-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'M2M Подписка', 'verbose_name_plural': 'M2M Подписки'},
        ),
    ]
